### ISSUE TITLE
Not working for `git add -p` diff files.

### ISSUE THREAD

**Issue by real-yfprojects** [caponetto/vscode-diff-viewer#23]
I am using VS Code as editor for git. When a run `git add -p somefile` and then enter `e` to edit the diff file in the default editor, the `.diff` file is opened in VS Code. The extension then reports that it couldn't find any diff structure in the file.
It would be really great if that wasn't the case and I was able to use the diff viewer for editing these diff files.

**Comment by caponetto** [comment]
Thanks for bringing this up, @real-yfprojects.
Since you're using VS Code to edit `*.diff` files generated by `git add -p`, you cannot have this extension installed.
The structure of `git add -p` is not compatible, only the ones generated by `git diff > somefile.diff`.
The only way would be using another editor or the CLI to edit the output of `git add -p`.

Anyway, there's no plan to provide the edition feature once this extension is only a viewer.
I'll also consider changing the extension pattern from `*.diff` to something else to avoid such conflicts.

**Comment by real-yfprojects** [comment]
Thank you for your immediate answer @caponetto.

I also noticed that it really is only a viewer. So this issue is obsolete.
Since visual code already has a great diff viewer build-in,  I uninstalled this extension again.
